version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: sdc_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    networks:
      - intranet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:13
    container_name: sdc_postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: fastapi_test
    networks:
      - intranet
    ports:
      - "5433:5432"  # 修改端口，避免與正式資料庫端口衝突
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  test:
    build: .
    container_name: sdc_fastapi_test
    depends_on:
      - postgres_test
      - app
    networks:
      - intranet
    volumes:
      - ./app:/code/app
    environment:
      - ENV=testing

  mariadb:
    image: mariadb:10.6
    container_name: sdc_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - intranet
    volumes:
      - mariadb_data:/var/lib/mysql

  pgadmin4:
    image: dpage/pgadmin4
    container_name: sdc_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - intranet
    ports:
      - "5050:80"
    depends_on:
      - postgres

  phpmyadmin:
    image: phpmyadmin
    container_name: sdc_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - intranet
    ports:
      - "8081:80"
    depends_on:
      - mariadb

  app:
    build: ./  
    container_name: sdc_fastapi_app
    environment:
      - OLLAMA_URL=http://ollama:11434
    restart: always
    networks:
      - intranet
    volumes:
      - ./app:/code/app
    ports:
      - "8080:8000"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_container
    restart: always
    networks:
      - intranet
    ports:
      - "11434:11434"
    command: "serve"


networks:
  intranet:
    driver: bridge

volumes:
  postgres_data:
  postgres_test_data:
  mariadb_data:
